### ISSUE TITLE
HTTP ERROR 500 after adding new item for sale

### ISSUE THREAD

**Issue by kendellmendoza** [denetwerkspecialist/Auctions#2]
Here is the error log:

Unknown error type: [2] A non-numeric value encountered on /var/www/html/select_category.php line 35
Unknown error type: [8] Undefined index: gewicht on /var/www/html/sell.php line 758
Unknown error type: [8] Undefined index: gewicht on /var/www/html/sell.php line 485

And HTTP 500 error screenshot:

![image](https://user-images.githubusercontent.com/32558172/67042007-ebc8c280-f0f4-11e9-911f-847a734a99fa.png)

**Comment by denetwerkspecialist** [comment]
Please inform us when it happend?
Do you use the default auctions categories?
Please describe it step by step

**Comment by kendellmendoza** [comment]
Can you tell me what Web Server, PHP and MySQL version you are running that is working?

**Comment by denetwerkspecialist** [comment]
HiWe upload the fix next week.We added the value weight to the database. Regards martinVerzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: kendellmendoza <notifications@github.com> Datum: 18-10-19  19:54  (GMT+01:00) Aan: denetwerkspecialist/Auctions <Auctions@noreply.github.com> Cc: denetwerkspecialist <info@denetwerkspecialist.com>, Comment <comment@noreply.github.com> Onderwerp: Re: [denetwerkspecialist/Auctions] HTTP ERROR 500 after adding new item for sale (#2) Can you tell me what Web Server, PHP and MySQL version you are running that is working?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/denetwerkspecialist/Auctions/issues/2?email_source=notifications\u0026email_token=ANKPS2YZXKEX4J4N7JHWX4TQPHZ47A5CNFSM4JB6UCP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBVKRQA#issuecomment-543860928",
"url": "https://github.com/denetwerkspecialist/Auctions/issues/2?email_source=notifications\u0026email_token=ANKPS2YZXKEX4J4N7JHWX4TQPHZ47A5CNFSM4JB6UCP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBVKRQA#issuecomment-543860928",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by denetwerkspecialist** [comment]
we will upload a new version next week with a fix for this

**Comment by denetwerkspecialist** [comment]
Please check our new release Community Edition 1.0.
Tomorrow we will release  Community Edition 1.0.1 where we add only dummy content with can be changed by the admin users

**Comment by denetwerkspecialist** [comment]
fixed in new release
